### ISSUE TITLE
leaks

### ISSUE THREAD

**Issue by eloi-duwer** [vroussea/RT#2]
ya plein de leaks askiparait, j'ai fait un dossier test_leaks dans la branche eloi, avec que le nouveau parser(compiler avec gcc srcs/rtv1.c srcs/init_*.c srcs/convert_to_hex.c srcs/list_funct.c srcs/libft.c srcs/get_infos.c srcs/get_next_line.c srcs/obj_infos.c srcs/check.c srcs/maths*.c srcs/make_new_obj.c -I ./includes). Ci dessous retour de valgrind lancé dessus:
![screen shot 2017-03-13 at 7 06 18 pm](https://cloud.githubusercontent.com/assets/23403392/23868577/351eaef6-0820-11e7-8902-b979a3ae364d.png)

bref, ALED

**Comment by ExtReMLapin** [comment]
Pour les leaks, fais ```leaks RT```


Valgrind c'est un peu comme les féministes qui crient pour rien.

**Comment by eloi-duwer** [comment]
bah leaks dit juste que ya des leaks et voila xD ca n'aide pas trop non plus.
'fin bref probleme réglé de tt facon
