### ISSUE TITLE
bug waves

### ISSUE THREAD

**Issue by eloi-duwer** [vroussea/RT#4]
![screen shot 2017-03-16 at 5 12 32 pm](https://cloud.githubusercontent.com/assets/23403392/24006381/e452dea4-0a6b-11e7-9801-c2896b6b6eb0.png)
la booleenne is_waves est de base initialisee a 0, sauf si on rencontre la balise <waves/>.
PB, ici aucune waves de base, pourtant on les retrouve sur 1 des 4 threads, le pb ne me semble pas venir de la lecture. any ideas?

**Comment by ExtReMLapin** [comment]
Pas de chance que ca vienne de mes conversions de  int en bool ?

**Comment by eloi-duwer** [comment]
yen n'a pas, la si on rencontre la balise on passe le bool a true, de base il est false, et le pop du bug est aléatoire

**Comment by ExtReMLapin** [comment]
J'ai trouvé source segfault sur le slack

**Comment by eloi-duwer** [comment]
bon, je suis tres con mais c'est réglé

**Comment by ExtReMLapin** [comment]
ui
